name: Build VCV Rack Plugin

on: [push, pull_request]

env:
  rack-plugin-toolchain-dir: /home/build/rack-plugin-toolchain
  
defaults:
  run:
    shell: bash

jobs:
  build:
    name: Windows x64 Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/qno/rack-plugin-toolchain:v2
      options: --user root
      
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build plugin
        run: |
          export PLUGIN_DIR=$GITHUB_WORKSPACE
          /home/build/rack-plugin-toolchain/compile-plugin.sh win-x64
