name: Build VCV Rack Plugin

on: [push, pull_request]

env:
  rack-plugin-toolchain-dir: /home/build/rack-plugin-toolchain
  
defaults:
  run:
    shell: bash

jobs:
  build:
    name: Windows x64 Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/qno/rack-plugin-toolchain-win-linux
      options: --user root
      
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build plugin
        run: |
          export PLUGIN_DIR=$GITHUB_WORKSPACE
          pushd /home/build/rack-plugin-toolchain
          make plugin-build-win-x64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: /home/build/rack-plugin-toolchain/plugin-build
          name: win-x64
